test_get_number_of_char (__main__.TestExercice) ... FAIL
test_get_number_of_words (__main__.TestExercice) ... FAIL
test_pair (__main__.TestExercice) ... FAIL
test_remove_third_char (__main__.TestExercice) ... ok
test_replace_char (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_get_number_of_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 65, in test_get_number_of_char
    "Mauvais calcul du nombre d'occurence du caractère"
AssertionError: Lists differ: [None, None, None] != [4, 1, 0]

First differing element 0:
None
4

- [None, None, None]
+ [4, 1, 0] : Mauvais calcul du nombre d'occurence du caractère

======================================================================
FAIL: test_get_number_of_words (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 81, in test_get_number_of_words
    "Mauvais calcul du nombre d'occurence du mot"
AssertionError: Lists differ: [None, None, None] != [2, 0, 1]

First differing element 0:
None
2

- [None, None, None]
+ [2, 0, 1] : Mauvais calcul du nombre d'occurence du mot

======================================================================
FAIL: test_pair (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 21, in test_pair
    'Mauvaise identification de la parité de la longueur de la chaine'
AssertionError: Lists differ: [False, False, False] != [True, False, False]

First differing element 0:
False
True

- [False, False, False]
+ [True, False, False] : Mauvaise identification de la parité de la longueur de la chaine

======================================================================
FAIL: test_replace_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 49, in test_replace_char
    'Erreur dans le remplacement de caractère'
AssertionError: Lists differ: [None, None, None] != ['hey yad!', 'bbbbbb', 'a1234']

First differing element 0:
None
'hey yad!'

- [None, None, None]
+ ['hey yad!', 'bbbbbb', 'a1234'] : Erreur dans le remplacement de caractère

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
